[package]
name = "pemmican"
version = "0.1.1-unstable"
authors = ["Mike Dilger <mike@optcomp.nz>"]
description = "Pemmican Web Framework"
license-file = "LICENCE"

[dependencies]
hyper = "0.11"
futures = "0.1"
futures-cpupool = "0.1"
chashmap = "2.2"
